### ISSUE TITLE
NX-OS Plattform selection

### ISSUE THREAD

**Issue by fenrir-itsec** [CiscoPSIRT/openVulnQuery#2]
Hi,

I think it is necessary to be able to specify the nx-os plattform (series) within the "get_by_nxos()" queries, since many versions within the different plattforms are identical, but have not the same vulnerability attributes. This would reduce false positives.

Also, if you use the Cisco Software Checker you have to specify the plattform (e.g. Cisco Nexus 3000 Series Switches) too.

Thanks!

**Comment by santosomar** [comment]
I completely agree. I will try to modify the client code soon to support the ability to do that selection.

**Comment by santosomar** [comment]
As a side note: I have opened an enhancement request for the API to support the listing of all the NX-OS and ACI platforms that are supported. This will allow the openVulnQuery and the end user/programmer to know which platforms are available (and subsequently to make queries).
