### ISSUE TITLE
API doesnt work anymore

### ISSUE THREAD

**Issue by vikdean** [CiscoPSIRT/openVulnQuery#27]
https://community.cisco.com/t5/services-discussions/openvulnquery-authorization-issues/td-p/4809299

Can confirm, it doesn't work anymore:

```
openVulnQuery  --product Cisco
Traceback (most recent call last):
  File "/usr/local/bin/openVulnQuery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/openVulnQuery/_library/main.py", line 58, in main
    client = query_client.OpenVulnQueryClient(**client_cfg)
  File "/usr/local/lib/python3.9/dist-packages/openVulnQuery/_library/query_client.py", line 72, in __init__
    self.auth_token = authorization.get_oauth_token(
  File "/usr/local/lib/python3.9/dist-packages/openVulnQuery/_library/authorization.py", line 22, in get_oauth_token
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://cloudsso.cisco.com/as/token.oauth2?client_id=XXXXX&client_secret=XXXXXX
```

**Comment by ngageby** [comment]
I have had similar issues with this and many samples on the web.  If you go to this URL https://developer.cisco.com/docs/psirt/#!api-reference/api-reference you will see that the API url is different depending on when you started you project.  If you update this sample to use the correct URL you should be fine. 
![image](https://user-images.githubusercontent.com/23490579/236898962-a43b437e-f9f4-4c1a-b242-18bc09d981b7.png)
You can see all the sample on the URL are not using the new URL only the note at the top helps.  

HTH

**Comment by vikdean** [comment]
> I have had similar issues with this and many samples on the web. If you go to this URL https://developer.cisco.com/docs/psirt/#!api-reference/api-reference you will see that the API url is different depending on when you started you project. If you update this sample to use the correct URL you should be fine. ![image](https://user-images.githubusercontent.com/23490579/236898962-a43b437e-f9f4-4c1a-b242-18bc09d981b7.png) You can see all the sample on the URL are not using the new URL only the note at the top helps.
> 
> HTH

Can you provide some more details please? Change what exactly and where to make openVulnQuery work with the new API URL?

**Comment by poxman** [comment]
Hello,
   The current code in github supports the new Token Endpoint:

REQUEST_TOKEN_URL = "https://id.cisco.com/oauth2/default/v1/token"

If you still have an old application registration and wish to use the old token endpoint (recommend migrating before it is shut down); just change the REQUEST_TOKEN_URL in the config.py back to the old one.

See https://developer.cisco.com/docs/psirt/#!api-changelog/version-20 for more details.

HTH.

**Comment by santosomar** [comment]
@poxman is absolutely correct. Additional information is located at: https://community.cisco.com/t5/security-knowledge-base/reminder-changes-to-cisco-apis-and-api-console/ta-p/4837122

**Comment by vikdean** [comment]
I've just registered a brand new app at https://apiconsole.cisco.com/; added the credentials to the credentials.json as instructed and ran the script:

```
openVulnQuery --config /home/vuln/credentials.json --all --csv /home/vuln/result.csv
Traceback (most recent call last):
  File "/usr/local/bin/openVulnQuery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/openVulnQuery/_library/main.py", line 58, in main
    client = query_client.OpenVulnQueryClient(**client_cfg)
  File "/usr/local/lib/python3.9/dist-packages/openVulnQuery/_library/query_client.py", line 72, in __init__
    self.auth_token = authorization.get_oauth_token(
  File "/usr/local/lib/python3.9/dist-packages/openVulnQuery/_library/authorization.py", line 22, in get_oauth_token
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://cloudsso.cisco.com/as/token.oauth2?client_id=xxxxx&client_secret=xxxxxxx
```

Any ideas what could be the problem?

**Comment by poxman** [comment]
Hello,
    Did you install via PIP/PIP3?  If so that code has yet to be updated because of an open bug.
    
    Pull the code direct from github that has the latest changes; which has the new token server endpoint.  You can see in the error requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://cloudsso.cisco.com/as/token.oauth2?client_id=xxxxx&client_secret=xxxxxxx that it is using the old token endpoint.

Thanks

**Comment by vikdean** [comment]
> Hello, Did you install via PIP/PIP3? If so that code has yet to be updated because of an open bug.
> 
> ```
> Pull the code direct from github that has the latest changes; which has the new token server endpoint.  You can see in the error requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://cloudsso.cisco.com/as/token.oauth2?client_id=xxxxx&client_secret=xxxxxxx that it is using the old token endpoint.
> ```
> 
> Thanks

I've used the pip version before.

Tried the one directly from Git; am I missing something? Is there a step I didnt do?

```
Traceback (most recent call last):
  File "/home/vuln/openVulnQuery/openVulnQuery/main.py", line 1, in <module>
    from ._library.main import main
ImportError: attempted relative import with no known parent package
```

**Comment by poxman** [comment]
Hello,
    A quick fix should be to run: `python3 -m openVulnQuery.main` from your /home/vuln/openVulnQuery/ directory.

    There are other solutions; however let me work with the owner of the code; to get the bug fixed that prevents us pushing the updates to PIP.

HTH
